import React, { useState, useEffect, useRef } from 'react';
import { Send, Shield, AlertTriangle, CheckCircle, OctagonAlert, Clock, ChevronRight, User, Bot, Plus, Trash2, ChevronDown, ChevronUp, Eye, FileCheck, PlayCircle } from 'lucide-react';

const STORAGE_KEY = 'trustlayer_chat_history_v1';

export default function ChatView({ onNewAction }) {
  const [threads, setThreads] = useState(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved) return JSON.parse(saved);
    } catch (e) {
      console.error('Error loading chat history:', e);
    }
    const initId = `thread-${Date.now()}`;
    return [
      {
        id: initId,
        title: 'New Governance Chat',
        created_at: new Date().toISOString(),
        messages: [
          {
            id: 'welcome',
            type: 'system',
            text: 'Welcome to TrustOps AI governed by TrustLayer AI. Every action proposal generated by the AI agent passes through Action Monitoring, Policy Engine, and Risk Engine before mock tools can execute.'
          }
        ]
      }
    ];
  });

  const [activeThreadId, setActiveThreadId] = useState(() => {
    return threads[0]?.id || `thread-${Date.now()}`;
  });

  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [expandedGovernance, setExpandedGovernance] = useState({});

  const messagesEndRef = useRef(null);

  // Save to localStorage whenever threads change
  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(threads));
    } catch (e) {
      console.error('Failed to persist chat history:', e);
    }
  }, [threads]);

  const threadsRef = useRef(threads);
  useEffect(() => {
    threadsRef.current = threads;
  }, [threads]);

  useEffect(() => {
    const updatePendingActions = async () => {
      let updated = false;
      const currentThreads = threadsRef.current;
      const newThreads = await Promise.all(currentThreads.map(async (t) => {
        const newMessages = await Promise.all(t.messages.map(async (m) => {
          if (
            m.sender === 'bot' &&
            m.data &&
            m.data.governance &&
            m.data.governance.decision === 'REQUIRE_APPROVAL' &&
            m.data.governance.status === 'PENDING_APPROVAL'
          ) {
            try {
              const actionId = m.data.action_proposal.action_id;
              const res = await fetch(`http://localhost:8000/api/actions/${actionId}`);
              if (res.ok) {
                const detail = await res.json();
                if (detail.status === 'EXECUTED' || detail.status === 'REJECTED') {
                  updated = true;
                  const params = detail.parameters || {};
                  const vendor = params.vendor || "ABC Suppliers";
                  const amount = params.amount || 50000;
                  let finalMsg = m.data.final_response;
                  if (detail.status === 'EXECUTED') {
                    finalMsg = `Successfully transferred ₹${amount.toLocaleString('en-IN')} to ${vendor}.`;
                  } else if (detail.status === 'REJECTED') {
                    finalMsg = `Payment request to ${vendor} was rejected.`;
                  }
                  return {
                    ...m,
                    data: {
                      ...m.data,
                      tool_result: detail.execution_result,
                      final_response: finalMsg,
                      governance: {
                        ...m.data.governance,
                        status: detail.status === 'EXECUTED' ? 'ALLOWED' : 'BLOCKED',
                        decision: detail.status === 'EXECUTED' ? 'ALLOW' : 'BLOCK',
                        explanation: detail.status === 'EXECUTED'
                          ? `Action approved by operator. Notes: ${detail.approval?.notes || ""}`
                          : `Action rejected by operator. Notes: ${detail.approval?.notes || ""}`
                      }
                    }
                  };
                }
              }
            } catch (e) {
              console.error('Error fetching action details:', e);
            }
          }
          return m;
        }));
        return { ...t, messages: newMessages };
      }));

      if (updated) {
        setThreads(newThreads);
      }
    };

    updatePendingActions();
    const interval = setInterval(updatePendingActions, 3000);
    return () => clearInterval(interval);
  }, []);

  const currentThread = threads.find((t) => t.id === activeThreadId) || threads[0];

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [currentThread?.messages, loading]);

  const handleNewChat = () => {
    const newId = `thread-${Date.now()}`;
    const newThread = {
      id: newId,
      title: 'New Governance Chat',
      created_at: new Date().toISOString(),
      messages: [
        {
          id: `sys-${Date.now()}`,
          type: 'system',
          text: 'New conversation started. Formulate request for TrustOps AI.'
        }
      ]
    };
    setThreads((prev) => [newThread, ...prev]);
    setActiveThreadId(newId);
  };

  const handleDeleteThread = (threadId, e) => {
    e.stopPropagation();
    if (threads.length <= 1) {
      handleNewChat();
      return;
    }
    const filtered = threads.filter((t) => t.id !== threadId);
    setThreads(filtered);
    if (activeThreadId === threadId) {
      setActiveThreadId(filtered[0].id);
    }
  };

  const toggleGovernance = (msgId) => {
    setExpandedGovernance((prev) => ({
      ...prev,
      [msgId]: !prev[msgId]
    }));
  };

  const demoScenarios = [
    {
      type: 'safe',
      color: '#10b981',
      bg: 'rgba(16, 185, 129, 0.12)',
      border: 'rgba(16, 185, 129, 0.35)',
      icon: '🟢',
      title: 'SAFE ACTION',
      prompt: 'Schedule a meeting with HR tomorrow at 10 AM.'
    },
    {
      type: 'approval',
      color: '#f59e0b',
      bg: 'rgba(245, 158, 11, 0.12)',
      border: 'rgba(245, 158, 11, 0.35)',
      icon: '🟡',
      title: 'APPROVAL REQUIRED',
      prompt: 'Create a payment of ₹50,000 to ABC Suppliers.'
    },
    {
      type: 'blocked',
      color: '#ef4444',
      bg: 'rgba(239, 68, 68, 0.12)',
      border: 'rgba(239, 68, 68, 0.35)',
      icon: '🔴',
      title: 'BLOCKED ACTION',
      prompt: 'Delete all customer records.'
    }
  ];

  const handleSend = async (customPrompt) => {
    const textToSend = customPrompt || prompt;
    if (!textToSend.trim() || loading) return;

    const userMsgId = `usr-${Date.now()}`;
    const userMsg = { id: userMsgId, sender: 'user', text: textToSend };

    // Update active thread with user message and update title if first user prompt
    setThreads((prevThreads) => {
      return prevThreads.map((t) => {
        if (t.id === activeThreadId) {
          const isFirstUserMsg = !t.messages.some((m) => m.sender === 'user');
          const newTitle = isFirstUserMsg ? textToSend.slice(0, 26) + (textToSend.length > 26 ? '...' : '') : t.title;
          return {
            ...t,
            title: newTitle,
            messages: [...t.messages, userMsg]
          };
        }
        return t;
      });
    });

    if (!customPrompt) setPrompt('');
    setLoading(true);

    try {
      const res = await fetch('http://localhost:8000/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: textToSend })
      });

      if (!res.ok) throw new Error(`Server returned HTTP ${res.status}`);

      const data = await res.json();
      const botMsgId = `bot-${Date.now()}`;
      const botMsg = { id: botMsgId, sender: 'bot', data: data };

      setThreads((prevThreads) => {
        return prevThreads.map((t) => {
          if (t.id === activeThreadId) {
            return {
              ...t,
              messages: [...t.messages, botMsg]
            };
          }
          return t;
        });
      });

      if (onNewAction) onNewAction();
    } catch (err) {
      const errMsg = {
        id: `err-${Date.now()}`,
        sender: 'system',
        error: true,
        text: `Error communicating with TrustLayer backend: ${err.message}. Ensure backend is running on http://localhost:8000.`
      };
      setThreads((prevThreads) => {
        return prevThreads.map((t) => {
          if (t.id === activeThreadId) {
            return { ...t, messages: [...t.messages, errMsg] };
          }
          return t;
        });
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="chat-main-wrapper">
      {/* Left Sidebar — Chat History */}
      <div className="chat-history-sidebar">
        <button className="new-chat-btn" onClick={handleNewChat}>
          <Plus size={18} /> + New Chat
        </button>

        <div style={{ fontSize: '0.75rem', fontWeight: 800, color: '#64748b', textTransform: 'uppercase', marginTop: '0.5rem' }}>
          Conversation Threads
        </div>

        <div className="chat-threads-list">
          {threads.map((t) => (
            <div
              key={t.id}
              className={`chat-thread-item ${t.id === activeThreadId ? 'active' : ''}`}
              onClick={() => setActiveThreadId(t.id)}
            >
              <span style={{ flex: 1, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                {t.title}
              </span>
              <button
                onClick={(e) => handleDeleteThread(t.id, e)}
                style={{ background: 'transparent', border: 'none', color: '#64748b', cursor: 'pointer', padding: '2px' }}
                title="Delete thread"
              >
                <Trash2 size={14} />
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* Main Chat Workspace */}
      <div className="chat-container">
        {/* Banner Header */}
        <div
          style={{
            background: 'rgba(99, 102, 241, 0.08)',
            border: '1px solid rgba(99, 102, 241, 0.25)',
            padding: '0.85rem 1.25rem',
            borderRadius: '14px',
            marginBottom: '1rem',
            display: 'flex',
            justify: 'space-between',
            alignItems: 'center'
          }}
        >
          <div>
            <div style={{ fontSize: '1.1rem', fontWeight: 800, color: '#ffffff', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <Bot size={22} color="#6366f1" />
              TRUSTOPS AI
              <span style={{ fontSize: '0.8rem', fontWeight: 700, color: '#a5b4fc', background: 'rgba(99,102,241,0.2)', padding: '3px 9px', borderRadius: '6px' }}>
                Governed by TrustLayer
              </span>
            </div>
          </div>
        </div>

        {/* 3 Prominent Quick Demo Scenario Buttons */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '0.85rem', marginBottom: '1rem' }}>
          {demoScenarios.map((sc, idx) => (
            <button
              key={idx}
              onClick={() => handleSend(sc.prompt)}
              disabled={loading}
              style={{
                background: sc.bg,
                border: `1px solid ${sc.border}`,
                borderRadius: '12px',
                padding: '0.85rem 1rem',
                textAlign: 'left',
                cursor: 'pointer',
                transition: 'all 0.2s ease',
                display: 'flex',
                flexDirection: 'column',
                gap: '0.3rem'
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.8rem', fontWeight: 800, color: sc.color }}>
                <span>{sc.icon}</span> {sc.title}
              </div>
              <div style={{ fontSize: '0.875rem', fontWeight: 600, color: '#ffffff', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                "{sc.prompt}"
              </div>
            </button>
          ))}
        </div>

        {/* Message Thread Scroll Container */}
        <div className="messages-list">
          {currentThread?.messages.map((msg) => {
            if (msg.type === 'system') {
              return (
                <div
                  key={msg.id}
                  className="glass-card"
                  style={{
                    background: msg.error ? 'rgba(239, 68, 68, 0.1)' : 'rgba(99, 102, 241, 0.08)',
                    borderColor: msg.error ? 'rgba(239, 68, 68, 0.3)' : 'rgba(99, 102, 241, 0.3)',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '0.75rem',
                    padding: '1rem 1.25rem'
                  }}
                >
                  <Shield size={22} color={msg.error ? '#ef4444' : '#6366f1'} />
                  <div style={{ fontSize: '0.95rem', color: msg.error ? '#fca5a5' : '#cbd5e1' }}>
                    {msg.text}
                  </div>
                </div>
              );
            }

            if (msg.sender === 'user') {
              return (
                <div
                  key={msg.id}
                  style={{
                    alignSelf: 'flex-end',
                    maxWidth: '80%',
                    background: 'linear-gradient(135deg, #1e293b 0%, #0f172a 100%)',
                    border: '1px solid rgba(255, 255, 255, 0.12)',
                    borderRadius: '18px 18px 2px 18px',
                    padding: '1rem 1.35rem',
                    boxShadow: '0 4px 14px rgba(0, 0, 0, 0.25)'
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.35rem' }}>
                    <User size={15} color="#94a3b8" />
                    <span style={{ fontSize: '0.8rem', color: '#94a3b8', fontWeight: 700 }}>YOU</span>
                  </div>
                  <div style={{ fontSize: '1rem', fontWeight: 500, lineHeight: 1.5 }}>{msg.text}</div>
                </div>
              );
            }

            if (msg.sender === 'bot' && msg.data) {
              const { action_proposal, governance, tool_result, final_response } = msg.data;
              const { risk, policy_checks, decision, explanation } = governance || {};
              const isGovOpen = !!expandedGovernance[msg.id];

              return (
                <div
                  key={msg.id}
                  style={{
                    alignSelf: 'flex-start',
                    width: '100%',
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '0.85rem'
                  }}
                >
                  {/* Human-Friendly Natural AI Response Bubble */}
                  <div
                    className="glass-card"
                    style={{
                      borderLeft: `5px solid ${
                        !governance
                          ? '#6366f1'
                          : decision === 'ALLOW'
                          ? '#10b981'
                          : decision === 'REQUIRE_APPROVAL'
                          ? '#f59e0b'
                          : '#ef4444'
                      }`,
                      padding: '1.25rem 1.5rem'
                    }}
                  >
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '0.75rem' }}>
                      <Bot size={22} color="#6366f1" />
                      <span style={{ fontSize: '0.95rem', fontWeight: 800, color: '#ffffff' }}>TRUSTOPS AI</span>
                      {governance ? (
                        <span className={`badge badge-${decision === 'ALLOW' ? 'allow' : decision === 'REQUIRE_APPROVAL' ? 'approval' : 'block'}`} style={{ marginLeft: 'auto' }}>
                          {decision === 'ALLOW' ? 'ALLOWED' : decision === 'REQUIRE_APPROVAL' ? 'APPROVAL REQ' : 'BLOCKED'}
                        </span>
                      ) : (
                        <span className="badge" style={{ marginLeft: 'auto', background: 'rgba(148, 163, 184, 0.15)', color: '#94a3b8', border: '1px solid rgba(148, 163, 184, 0.3)' }}>
                          UNSUPPORTED
                        </span>
                      )}
                    </div>

                    {/* Prominent Natural Response Text */}
                    <div style={{ fontSize: '1.05rem', color: '#ffffff', lineHeight: 1.6, whiteSpace: 'pre-wrap', fontWeight: 500 }}>
                      {final_response}
                    </div>

                    {/* Collapsible Accordion Trigger */}
                    {governance && action_proposal && (
                      <div style={{ marginTop: '1rem', paddingTop: '0.75rem', borderTop: '1px solid var(--border-color)' }}>
                        <button
                          onClick={() => toggleGovernance(msg.id)}
                          style={{
                            background: 'rgba(255,255,255,0.05)',
                            border: '1px solid var(--border-color)',
                            color: '#a5b4fc',
                            padding: '0.45rem 0.85rem',
                            borderRadius: '8px',
                            fontSize: '0.85rem',
                            fontWeight: 700,
                            cursor: 'pointer',
                            display: 'inline-flex',
                            alignItems: 'center',
                            gap: '0.4rem'
                          }}
                        >
                          {isGovOpen ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                          {isGovOpen ? 'Hide TrustLayer Governance' : 'View TrustLayer Governance'}
                        </button>
                      </div>
                    )}
                  </div>

                  {/* Collapsible TrustLayer Technical Details */}
                  {governance && action_proposal && isGovOpen && (
                    <div
                      className="glass-card"
                      style={{
                        background: 'rgba(10, 14, 23, 0.96)',
                        borderColor: 'rgba(99, 102, 241, 0.35)',
                        display: 'flex',
                        flexDirection: 'column',
                        gap: '1.25rem',
                        padding: '1.5rem',
                        borderRadius: '16px',
                        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.35)'
                      }}
                    >
                      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid rgba(255,255,255,0.08)', paddingBottom: '0.75rem' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
                          <Shield size={20} color="#6366f1" />
                          <span style={{ fontSize: '0.9rem', fontWeight: 800, color: '#ffffff', letterSpacing: '0.04em' }}>
                            COMPLETE AI-TO-TRUSTLAYER GOVERNANCE TRACE
                          </span>
                        </div>
                        <span style={{ fontFamily: 'var(--font-mono)', fontSize: '0.8rem', color: '#a5b4fc', background: 'rgba(99,102,241,0.15)', padding: '3px 8px', borderRadius: '6px' }}>
                          {action_proposal.action_id}
                        </span>
                      </div>

                      {/* 6 Structured Governance Trace Sections */}
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>

                        {/* 1. AI ACTION PROPOSAL */}
                        <div style={{ background: 'rgba(99, 102, 241, 0.06)', border: '1px solid rgba(99, 102, 241, 0.25)', borderRadius: '12px', padding: '1rem' }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.6rem' }}>
                            <Bot size={18} color="#818cf8" />
                            <span style={{ fontSize: '0.85rem', fontWeight: 800, color: '#818cf8', textTransform: 'uppercase' }}>
                              1. AI Action Proposal
                            </span>
                            <span style={{ fontSize: '0.75rem', color: '#94a3b8', marginLeft: 'auto' }}>
                              Generated by AI Agent/LLM from user request
                            </span>
                          </div>

                          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(170px, 1fr))', gap: '0.6rem', marginBottom: '0.6rem' }}>
                            <div style={{ background: 'rgba(0,0,0,0.3)', padding: '0.5rem 0.75rem', borderRadius: '8px' }}>
                              <span style={{ fontSize: '0.7rem', color: '#64748b', display: 'block', fontWeight: 600 }}>ACTION ID</span>
                              <span style={{ fontFamily: 'var(--font-mono)', fontSize: '0.85rem', color: '#38bdf8', fontWeight: 700 }}>
                                {action_proposal.action_id}
                              </span>
                            </div>
                            <div style={{ background: 'rgba(0,0,0,0.3)', padding: '0.5rem 0.75rem', borderRadius: '8px' }}>
                              <span style={{ fontSize: '0.7rem', color: '#64748b', display: 'block', fontWeight: 600 }}>AGENT ID</span>
                              <span style={{ fontFamily: 'var(--font-mono)', fontSize: '0.85rem', color: '#cbd5e1', fontWeight: 600 }}>
                                {action_proposal.agent_id || 'trustops-agent'}
                              </span>
                            </div>
                            <div style={{ background: 'rgba(0,0,0,0.3)', padding: '0.5rem 0.75rem', borderRadius: '8px' }}>
                              <span style={{ fontSize: '0.7rem', color: '#64748b', display: 'block', fontWeight: 600 }}>SESSION ID</span>
                              <span style={{ fontFamily: 'var(--font-mono)', fontSize: '0.85rem', color: '#cbd5e1', fontWeight: 600 }}>
                                {action_proposal.session_id}
                              </span>
                            </div>
                            <div style={{ background: 'rgba(0,0,0,0.3)', padding: '0.5rem 0.75rem', borderRadius: '8px' }}>
                              <span style={{ fontSize: '0.7rem', color: '#64748b', display: 'block', fontWeight: 600 }}>TOOL</span>
                              <span style={{ fontFamily: 'var(--font-mono)', fontSize: '0.85rem', color: '#a78bfa', fontWeight: 700 }}>
                                {action_proposal.tool}
                              </span>
                            </div>
                            <div style={{ background: 'rgba(0,0,0,0.3)', padding: '0.5rem 0.75rem', borderRadius: '8px' }}>
                              <span style={{ fontSize: '0.7rem', color: '#64748b', display: 'block', fontWeight: 600 }}>OPERATION</span>
                              <span style={{ fontFamily: 'var(--font-mono)', fontSize: '0.85rem', color: '#38bdf8', fontWeight: 700 }}>
                                {action_proposal.operation}
                              </span>
                            </div>
                            <div style={{ background: 'rgba(0,0,0,0.3)', padding: '0.5rem 0.75rem', borderRadius: '8px' }}>
                              <span style={{ fontSize: '0.7rem', color: '#64748b', display: 'block', fontWeight: 600 }}>REQUESTED AT</span>
                              <span style={{ fontFamily: 'var(--font-mono)', fontSize: '0.75rem', color: '#94a3b8' }}>
                                {action_proposal.requested_at}
                              </span>
                            </div>
                          </div>

                          <div>
                            <span style={{ fontSize: '0.7rem', color: '#94a3b8', fontWeight: 700, textTransform: 'uppercase', display: 'block', marginBottom: '0.25rem' }}>
                              PARAMETERS
                            </span>
                            <div className="code-block" style={{ margin: 0, padding: '0.6rem 0.8rem', fontSize: '0.8rem' }}>
                              <pre style={{ margin: 0 }}>{JSON.stringify(action_proposal.parameters || {}, null, 2)}</pre>
                            </div>
                          </div>
                        </div>

                        {/* 2. TRUSTLAYER ACTION MONITOR */}
                        <div style={{ background: 'rgba(14, 165, 233, 0.06)', border: '1px solid rgba(14, 165, 233, 0.25)', borderRadius: '12px', padding: '1rem' }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.4rem' }}>
                            <Eye size={18} color="#38bdf8" />
                            <span style={{ fontSize: '0.85rem', fontWeight: 800, color: '#38bdf8', textTransform: 'uppercase' }}>
                              2. TrustLayer Action Monitor
                            </span>
                          </div>
                          <p style={{ fontSize: '0.85rem', color: '#cbd5e1', margin: 0, lineHeight: 1.5 }}>
                            TrustLayer intercepted and monitored AI proposal <code style={{ color: '#38bdf8' }}>{action_proposal.action_id}</code>. The requested operation was locked in isolation and routed to the Policy and Risk engines before any tools could execute.
                          </p>
                        </div>

                        {/* 3. POLICY EVALUATION */}
                        <div style={{ background: 'rgba(168, 85, 247, 0.06)', border: '1px solid rgba(168, 85, 247, 0.25)', borderRadius: '12px', padding: '1rem' }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
                            <FileCheck size={18} color="#c084fc" />
                            <span style={{ fontSize: '0.85rem', fontWeight: 800, color: '#c084fc', textTransform: 'uppercase' }}>
                              3. Policy Evaluation
                            </span>
                          </div>
                          {policy_checks && policy_checks.length > 0 ? (
                            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                              {policy_checks.map((pol, pIdx) => (
                                <div key={pIdx} style={{ background: 'rgba(0,0,0,0.3)', padding: '0.65rem 0.85rem', borderRadius: '8px', borderLeft: `3px solid ${pol.status === 'BLOCK' ? '#ef4444' : '#f59e0b'}` }}>
                                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.25rem' }}>
                                    <span style={{ fontWeight: 700, color: '#ffffff', fontSize: '0.85rem' }}>
                                      {pol.policy_id} — {pol.policy_name}
                                    </span>
                                    <span className={`badge badge-${pol.status === 'BLOCK' ? 'block' : 'approval'}`}>
                                      {pol.status} ({pol.severity})
                                    </span>
                                  </div>
                                  <div style={{ fontSize: '0.8rem', color: '#cbd5e1' }}>
                                    {pol.message}
                                  </div>
                                </div>
                              ))}
                            </div>
                          ) : (
                            <div style={{ background: 'rgba(0,0,0,0.2)', padding: '0.5rem 0.75rem', borderRadius: '8px', fontSize: '0.85rem', color: '#10b981', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                              <CheckCircle size={15} color="#10b981" /> All policy checks passed. No violations triggered.
                            </div>
                          )}
                        </div>

                        {/* 4. RISK ASSESSMENT */}
                        <div style={{ background: 'rgba(245, 158, 11, 0.06)', border: '1px solid rgba(245, 158, 11, 0.25)', borderRadius: '12px', padding: '1rem' }}>
                          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.6rem' }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                              <AlertTriangle size={18} color="#fbbf24" />
                              <span style={{ fontSize: '0.85rem', fontWeight: 800, color: '#fbbf24', textTransform: 'uppercase' }}>
                                4. Risk Assessment
                              </span>
                            </div>
                            <span className={`badge badge-${risk?.level?.toLowerCase() || 'low'}`}>
                              SCORE: {risk?.score ?? 0}/100 ({risk?.level || 'LOW'})
                            </span>
                          </div>
                          <div style={{ fontSize: '0.85rem', color: '#e2e8f0', marginBottom: '0.5rem' }}>
                            {risk?.explanation || 'Risk assessment completed.'}
                          </div>
                          {risk?.factors && Object.keys(risk.factors).length > 0 && (
                            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))', gap: '0.4rem' }}>
                              {Object.entries(risk.factors).map(([factorKey, factorVal]) => (
                                <div key={factorKey} style={{ background: 'rgba(0,0,0,0.3)', padding: '0.4rem 0.6rem', borderRadius: '6px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                  <span style={{ fontSize: '0.7rem', color: '#94a3b8', textTransform: 'capitalize' }}>
                                    {factorKey.replace(/_/g, ' ')}
                                  </span>
                                  <span style={{ fontSize: '0.75rem', fontWeight: 700, color: factorVal > 5 ? '#f59e0b' : '#38bdf8' }}>
                                    {factorVal}
                                  </span>
                                </div>
                              ))}
                            </div>
                          )}
                        </div>

                        {/* 5. GOVERNANCE DECISION */}
                        <div
                          style={{
                            background: decision === 'ALLOW' ? 'rgba(16, 185, 129, 0.08)' : decision === 'REQUIRE_APPROVAL' ? 'rgba(245, 158, 11, 0.08)' : 'rgba(239, 68, 68, 0.08)',
                            border: `1px solid ${decision === 'ALLOW' ? 'rgba(16, 185, 129, 0.3)' : decision === 'REQUIRE_APPROVAL' ? 'rgba(245, 158, 11, 0.3)' : 'rgba(239, 68, 68, 0.3)'}`,
                            borderRadius: '12px',
                            padding: '1rem'
                          }}
                        >
                          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.4rem' }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                              <Shield size={18} color={decision === 'ALLOW' ? '#10b981' : decision === 'REQUIRE_APPROVAL' ? '#f59e0b' : '#ef4444'} />
                              <span style={{ fontSize: '0.85rem', fontWeight: 800, color: decision === 'ALLOW' ? '#10b981' : decision === 'REQUIRE_APPROVAL' ? '#f59e0b' : '#ef4444', textTransform: 'uppercase' }}>
                                5. Governance Decision: {decision}
                              </span>
                            </div>
                            <span className={`badge badge-${decision === 'ALLOW' ? 'allow' : decision === 'REQUIRE_APPROVAL' ? 'approval' : 'block'}`}>
                              {decision === 'ALLOW' ? 'ALLOWED' : decision === 'REQUIRE_APPROVAL' ? 'HELD FOR APPROVAL' : 'BLOCKED'}
                            </span>
                          </div>
                          <p style={{ fontSize: '0.85rem', color: '#e2e8f0', margin: 0, lineHeight: 1.5 }}>
                            {explanation || (decision === 'ALLOW' ? 'Action allowed for execution.' : decision === 'REQUIRE_APPROVAL' ? 'Action requires human authorization before tool execution.' : 'Action blocked by security governance policy.')}
                          </p>
                        </div>

                        {/* 6. TOOL EXECUTION */}
                        <div style={{ background: 'rgba(255, 255, 255, 0.03)', border: '1px solid rgba(255, 255, 255, 0.1)', borderRadius: '12px', padding: '1rem' }}>
                          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                              <PlayCircle size={18} color={tool_result?.status === 'SUCCESS' ? '#10b981' : tool_result ? '#ef4444' : '#64748b'} />
                              <span style={{ fontSize: '0.85rem', fontWeight: 800, color: '#ffffff', textTransform: 'uppercase' }}>
                                6. Tool Execution
                              </span>
                            </div>
                            <span style={{ fontSize: '0.75rem', fontWeight: 700, color: tool_result?.status === 'SUCCESS' ? '#10b981' : tool_result ? '#ef4444' : '#f59e0b' }}>
                              {decision === 'BLOCK' ? 'EXECUTION PREVENTED (BLOCKED)' : decision === 'REQUIRE_APPROVAL' && !tool_result ? 'PENDING OPERATOR APPROVAL' : tool_result?.status === 'SUCCESS' ? 'EXECUTED (SUCCESS)' : 'NOT EXECUTED'}
                            </span>
                          </div>
                          {tool_result ? (
                            <div>
                              <div className="code-block" style={{ margin: 0, padding: '0.6rem 0.8rem', fontSize: '0.8rem' }}>
                                <pre style={{ margin: 0 }}>{JSON.stringify(tool_result, null, 2)}</pre>
                              </div>
                            </div>
                          ) : (
                            <div style={{ fontSize: '0.8rem', color: '#94a3b8', fontStyle: 'italic' }}>
                              {decision === 'BLOCK' ? 'Tool execution was prohibited by TrustLayer policy.' : 'Tool execution is paused until approved in the Approvals Queue.'}
                            </div>
                          )}
                        </div>

                      </div>
                    </div>
                  )}
                </div>
              );
            }

            return null;
          })}

          {loading && (
            <div className="glass-card" style={{ display: 'flex', alignItems: 'center', gap: '0.85rem', padding: '1rem 1.25rem' }}>
              <Shield size={22} color="#6366f1" className="animate-spin" />
              <span style={{ fontSize: '0.95rem', color: '#cbd5e1', fontWeight: 600 }}>
                TrustOps AI analyzing request & evaluating through TrustLayer...
              </span>
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>

        {/* Input Form */}
        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleSend();
          }}
          className="chat-input-area"
        >
          <input
            type="text"
            className="chat-input"
            placeholder="Ask TrustOps AI to perform an action (e.g. 'Create a payment of ₹5,000 to XYZ Traders')..."
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            disabled={loading}
          />
          <button type="submit" className="send-btn" disabled={loading || !prompt.trim()}>
            <Send size={18} />
            Evaluate Request
          </button>
        </form>
      </div>
    </div>
  );
}
